### ISSUE TITLE
Support for compression

### ISSUE THREAD

**Issue by EddieOne** [rafaeldias/swf-reader#3]
Hi,

I have been getting reports of this error,

/home/upload/server/shared/node_modules/swf-reader/index.js:57
        uncompressed_buff = Buffer.concat([swf.slice(0, 8), lzma.uncompressFil
                                                                 ^
TypeError: Object #<Object> has no method 'uncompressFile'
    at uncompress (/home/upload/server/shared/node_modules/swf-reader/index.js:57:66)
    at /home/upload/server/shared/node_modules/swf-reader/index.js:135:7
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)

**Comment by EddieOne** [comment]
I found an alternate package. If any one wants to see it,
https://github.com/ankakaak/node-imageinfo
